Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/03/2022
Var
   // Seção de Declarações das variáveis
   c, n, t : inteiro

Inicio
    //Seção de Comandos, procedimento, funções, operadores, etc...
   c <- 0
   repita
      escreva( c, "...")
      c <- c+1
   ate (c > 10)




Fimalgoritmo